//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Goals>();
            }
        }
    }
    public partial class Goals
    {
        [PrimaryKey, AutoIncrement]
        public Int64 id { get; set; }
        
        public String goal_name { get; set; }
        
        public Double? target_amount { get; set; }
        
        public Double? amount_now { get; set; }
        
        public String date_deadline { get; set; }
        
        public String additional_notes { get; set; }
        
        public Double? goal_progress { get; set; }
        
    }
    
}
